language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install: "cpanm Module::Build::Prereqs::FromCPANfile Devel::Hide Data::Focus"
script: "perl Build.PL && ./Build && ./Build test && echo '------' && PERL5OPT=MDevel::Hide DEVEL_HIDE_PM=Data::Focus DEVEL_HIDE_VERBOSE=0 ./Build test"
